#!/usr/bin/python3

"""
A simple daemon run from systemd
Wake up once a minute, see if the kiosk configuration for this system's role has changed
If so, shoot firefox and let the kiosknanny restart it
"""

import urllib.request
import json
import subprocess
import pprint
import time

kioskRole='kiosk.role'
kioskCurrent='kiosk-current.url'
kiosksURLConfig='kiosk-config.url'
defaultURL = "https://wx.stfyc-wx.com"
defaultConfigURL = "http://10.0.0.22/Kiosks.json"

sleepInterval = 60

def kioskCheck():
    try:
        with open(kiosksURLConfig, 'r') as f:
            kiosksURL = f.read().rstrip() # trim trailing white space from role
    except:
        kiosksURL = defaultConfigURL

    try:
        with open(kioskRole, 'r') as f:
            role = f.read().rstrip() # trim trailing white space from role
    except:
        role = "Test"

    try:
        with open(kioskCurrent, 'r') as f:
            currentURL = f.read().rstrip()
    except:
        currentURL = defaultURL;

    try:
        single = urllib.request.urlopen(kiosksURL).read().decode('utf-8')
    except urllib.error.URLError as e:
        print(f"urllib error: {e}")
        return;

    double = single.replace("'", '"')
    kiosks = json.loads(double)

    #pprint.pp(kiosks)

    scene = kiosks["Roles"][role]
    url = kiosks["Scenes"][scene]
    urlString = "URL='%s'" % (url)

    if urlString != currentURL:
        # shoot firefox, let nanny restart it
        try:
            print("kioskcheck killing firefox")
            result = subprocess.run(['killall', 'firefox'], capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            print("killall failed: %r" % (e.output))

        with open(kioskCurrent, 'w') as f:
            f.write(urlString)
        print("kioskcheck new url %r" % (url))
        
if __name__ == '__main__':
    while (True):
        kioskCheck()
        time.sleep(sleepInterval)
